version: "3.8"
services:
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    restart: always
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=ab8mbu3t053tEn8
      - MSSQL_COLLATION=Thai_CI_AS
  app:
    image: web_api_smart_locker
    ports:
      - "5000:5000"
    depends_on:
      - sql_server