version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./setup_certbot.sh:/usr/local/bin/setup_certbot.sh
      - ./default.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - DOMAIN=alphaalpaca.xyz
    ports:
      - "80:80"
    entrypoint: /usr/local/bin/setup_certbot.sh
    command: nginx -g "daemon off;"
