version: '3.7'

services:
  reverseproxy:
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    ports:
      - "443:443" 
      - "80:80" 
    restart: always

  api:
    depends_on:
      - reverseproxy 
    build:
      context: .
      dockerfile: MyWebApiProject/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5000      
    ports:
      - "5000:5000"  
    restart: always